### ISSUE TITLE
Consider making the build reproducible by default

### ISSUE THREAD

**Issue by ppalaga** [aalmiray/kordamp-gradle-plugins#47]
Your blog post [1] says

> All JARs have their manifest enriched with additional entries such as build date/time/revision and more

I'd like to point out that adding clock time makes the build non-reproducible over time - i.e. the same source tree built at two occasions will produce binarily different artifacts. 

I see that having some date in manifest is practical. You may want to take the date of the last commit instead of the clock time.

Of course, this is not the only issue breaking the build reproducibility. The ZIP entry timestamps in JARs, WARs, etc. is another important one. Not sure how you handle those. Anyway, build reproducibility is goal worthwhile for making the defaults compatible with it.

[1] http://andresalmiray.com/the-gradle-pom/

**Comment by aalmiray** [comment]
Indeed. The JAR manifest is only enriched when `config.release` is set to `true`. See https://aalmiray.github.io/kordamp-gradle-plugins/#_org_kordamp_gradle_jar

Also, the DSL entry for `buildInfo` has a `clearTime` setting that will set the time to `0` even when the manifest is enriched. See https://aalmiray.github.io/kordamp-gradle-plugins/#_org_kordamp_gradle_buildinfo_dsl

Regular usage scenario is to run your build with `release = false` (the default) and only trigger manifest enrichment when you're ready to post a release (whether is a snapshot or a final release it's up to you).

Does this make sense? 😄

**Comment by ppalaga** [comment]
> The JAR manifest is only enriched when `config.release` is set to `true`

Which means that releases are non-reproducible by default. Anybody on any machine at any time should be able to rebuild and get binarily equal artifacts. I think it would be better if those environment and time dependent entries were not present in the manifest by default. See e.g. https://reproducible-builds.org/

**Comment by aalmiray** [comment]
Yes, that's the case for non-releases. Consider tools such as Gradle and Maven

    $ mvn --version
    Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
    Maven home: /Users/aalmiray/.sdkman/candidates/maven/current
    Java version: 1.8.0_191, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre
    Default locale: en_CH, platform encoding: UTF-8
    OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"

    $ gradle --version

    ------------------------------------------------------------
    Gradle 4.10.2
    ------------------------------------------------------------

    Build time:   2018-09-19 18:10:15 UTC
    Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

    Kotlin DSL:   1.0-rc-6
    Kotlin:       1.2.61
    Groovy:       2.4.15
    Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
    JVM:          1.8.0_191 (Oracle Corporation 25.191-b12)
    OS:           Mac OS X 10.13.6 x86_64

You'll never get the same timestamp even if the git hash is the same when you make a build in two different locations. 

However if the date/time options in the JAR manifest prove to be a problem, they can be disable them with `skipBuildDate` and `skipBuildTime`. The values will still be computed but won't be added to the manifest, this means you'll be able to grab those values and place them in another resource file or any other location you deem adequate for your needs. 😄

**Comment by ppalaga** [comment]
This not only a matter of whether I can make my own build reproducible using your tool. Sure I can, you offer the `skip*` options - that's all nice. 

What I am trying here, is to persuade you to enable the good practice by default (also for releases). If you keep the defaults as they are now, the wrong practice will prevail and it will be harder to ensure that third party artifacts I get from a random public repo were build from some particular sources.

You are creating a great tool and it would be a pity to miss the occasion to bring more trust into software development and delivery.

**Comment by aalmiray** [comment]
Fair enough. Releases may not have time sensitive data affecting their reproducible status, however there has to be one canonical release where this is true.

The current default settings make every release a canonical one, and that’s the point we’re debating, right?

What would you like this feature to work? At some point a flag must trigger the change, isn’t it?

**Comment by ppalaga** [comment]
> Fair enough. Releases may not have time sensitive data affecting their 
> reproducible status, however there has to be one canonical release where 
> this is true.
> 
> The current default settings make every release a canonical one, and 
> that’s the point we’re debating, right?

Yes, the build time and environment sensitive inputs currently added by default are the issue.

You seem to imply that they are the thing making the given build cannonical release? I am not sure I follow. Could you please explain that?

> What would you like this feature to work? At some point a flag must 
> trigger the change, isn’t it?

I do not see any harm in leaving the build time (and eventually also other environment related entries) out of the manifest by default.

Those entries are interesting, they help to understand some facts about the artifact, but they are not a must. They are not required by any standard. Moreover, (at least for some of them) replacements can be found that do not harm the reproducibility:

* As I said, the time of the last commit can be taken instead of the build clock time. 
* Author of the last commit can be used instead of the OS user performing the commit (they are often the same, and maybe the committer is even more interesting).
* etc.

Maybe I should better explain why the topic of build reproducibility is important:

As I said earlier, it helps to create more trust between an artifact consumer and the whole chain of parties that stand between him and the source code. If the build of an artifact is reproducible/deterministic, then the consumer may perform the build himself and assert that the whole delivery chain is trustful by a simple binary comparison of the artifacts.

In addition to trust I can name one more reason why build reproduciility is important. Companies relying on opensource often want to depend only on such artifacts that they can fix (read: fix and re-build) themselves. How can such a company make sure it can correctly build an artifact? It just tries to build it as good as it can and then it simply compares the resulting artifacts with the "cannonical" ones coming from a public artifact repository. The fact that the self-made artifacts are identical with the third party ones serves as a proof that the company knows the proper build process. BTW, the company I work for is doing this all the time. 

Does this make sense?

**Comment by aalmiray** [comment]
I see. Values that rely on environment settings and time/date will certainly cause non-reproducible builds. Fortunately these values are not injected in the manifest by default. However, setting the `release` flag to `true` will inject these values. Some values may be skipped if their corresponding `skip*` flag is set.

Looking at the 6 values that can be set we can only guarantee that the commit hash will identical.  Someone may update the gradle wrapper, this will make  `CreatedBy` differ. Picking the name of the current user may also case `BuiltBy` to be different. If we pick the commit author that would make the value resilient to change but might not make sense when the release is posted by a CI/CD pipeline (someone perhaps would like to know which node/server created the release).

Having the manifest (or any other resources that's packaged within the JAR, such a properties file) being enriched with environment sensitive values will make the artifact differ slightly. Calculating an MD5 checksum on artifacts that point form the same commit hash will yield different results, even if built with the same JDK, on the same machine, and by the same user.

Is it enough to compare artifacts as black boxes, using an MD5 checksum? Some will certainly see it as the only way. Others will look into the metadata contained within the artifact to further verify equality.

I think that having the manifest enrichment be protected by a flag is good enough for now. Developers have the choice to make no enrichment by default, enrich with their own attributes/values (most likely causing unreproducible artifacts), or enrich with the defaults given by this plugin. I've come across many scenarios with customers when knowing who, where, and when an artifact was produced was a must, besides by how and form which commit? Why, because developers used to push multiple releases without bumping version numbers (yes, this happens, yes it's bad, yes it was inertia what prevented the team from following better practices), we had to put a stop, automated metadata checks allowed us to make the jump.

I understand if you still have a different perspective on the subject. I definitely would like to support as many best practices as possible while still being flexible for those cases where the suboptimal is required. I do believe in choices rather than following just one path.

**Comment by ppalaga** [comment]
@aalmiray thanks for taking care to understand my point. Yes, I agree that all those options have their audience and I agree it is good that you offer them. I can only re-state that you are creating a great tool that has a potential to become popular. Due to this fact, you have a great power to impact not only the direct users of your tool, but also the rest of the JVM ecosystem. The defaults you choose will be used unchanged by the majority of your users. Thus, please, choose your defaults wisely.

If reproducibility is not important enough for you to become a part of your opinionated default, could please reproducibility at least get some exposure in the documentation of the options that make the build non-reproducible?

**Comment by aalmiray** [comment]
Yes, of course. I can add a section on reproducibility :-)

**Comment by ppalaga** [comment]
Here a story that illustrates the need for having means to check that public artifact repositories are not cheating: https://blog.autsoft.hu/a-confusing-dependency/
